kind: role
metadata:
  name: sombernet-admins
spec:
  allow:
    host_sudoers:
    - "ALL=(ALL)\tNOPASSWD: ALL"
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - '{{internal.logins}}'
    node_labels:
      tenant: 'sombernet'
      environment: '*'
  deny: {}
  options:
    cert_format: standard
    create_host_user: true
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v6
